networks:
  dspacenet:
    ipam:
      config:
        # Define a custom subnet for our DSpace network, so that we can easily trust requests from host to container.
        # If you customize this value, be sure to customize the 'proxies.trusted.ipranges' env variable below.
        - subnet: 172.24.0.0/16
services:
  # DSpace (backend) webapp container
  dspace:
    restart: unless-stopped
    container_name: dspace
    environment:
      POSTGRES_DB_HOST: dspacedb
      POSTGRES_DB_PORT: 5432
      POSTGRES_USER: dspace
      POSTGRES_PASSWORD: dspace
      POSTGRES_SCHEMA: dspace
      POSTGRES_ADMIN_USER: postgres
      POSTGRES_ADMIN_PASSWORD: postgres
      ADMIN_EMAIL: ADMIN_EMAIL
      ADMIN_FIRSTNAME: ADMIN_FIRSTNAME
      ADMIN_LASTNAME: ADMIN_LASTNAME
      ADMIN_PASSWD: ADMIN_PASSWD
      # Below syntax may look odd, but it is how to override dspace.cfg settings via env variables.
      # See https://github.com/DSpace/DSpace/blob/main/dspace/config/config-definition.xml
      # __P__ => "." (e.g. dspace__P__dir => dspace.dir)
      # __D__ => "-" (e.g. google__D__metadata => google-metadata)
      # dspace.dir: Must match with Dockerfile's DSPACE_INSTALL directory.
      dspace__P__dir: /dspace
      # Uncomment to set a non-default value for dspace.server.url or dspace.ui.url
      dspace__P__server__P__url: http://localhost:8080/server
      dspace__P__ui__P__url: http://localhost:4000
      dspace__P__name: NAME
      websvc__P__opensearch__P__shortname: SHORT_NAME
      # db.url: Ensure we are using the 'dspacedb' image for our database
      db__P__url: 'jdbc:postgresql://dspacedb:5432/dspace'
      # solr.server: Ensure we are using the 'dspacesolr' image for Solr
      solr__P__server: http://dspacesolr:8983/solr
      # proxies.trusted.ipranges: This setting is required for a REST API running in Docker to trust requests
      # from the host machine. This IP range MUST correspond to the 'dspacenet' subnet defined above.
      proxies__P__trusted__P__ipranges: '172.24.0'
      handle__P__prefix: 123456789
      LOGGING_CONFIG: /dspace/config/log4j2-container.xml
      webui__P__itemlist__P__sort__D__option__P__2: dateissued:dcterms.available:date
      webui__P__itemlist__P__sort__D__option__P__4: type:dc.type:text
      webui__P__feed__P__item__P__date: dateissued:dcterms.available:date
      xmlui__P__google__P__analytics__P__key: ''
      google__P__analytics__P__key: ''
      webui__P__browse__P__vocabularies__P__disabled: srsc
      mail__P__server: ''
      mail__P__server__P__username: ''
      mail__P__server__P__password: ''
      mail__P__server__P__port: ''
      mail__P__from__P__address: ''
      mail__P__feedback__P__recipient: ''
      feedback__P__recipient: ''
      mail__P__admin: ''
      mail__P__alert__P__recipient: ''
      mail__P__registration__P__notify: ''
      request__P__item__P__helpdesk__P__override: 'false'
      CONFIG_SIDEBAR_DISCOVERY_FACET_LIMIT: 10
      webui__P__browse__P__index__P__1: 'dateissued:item:dateissued'
      webui__P__browse__P__index__P__2: 'author:metadata:dc.contributor.*\,dc.creator:text'
      webui__P__browse__P__index__P__3: 'title:item:title'
      webui__P__browse__P__index__P__4: 'subject:metadata:dc.subject.*:text'
    image: "${DOCKER_OWNER:-dspace}/dspace:${DSPACE_VER:-dspace-7_x}"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dspacedb
    networks:
      - dspacenet
    ports:
      - published: 8080
        target: 8080
      - published: 8009
        target: 8009
      - published: 8000
        target: 8000
      - published: 2641
        target: 2641
    stdin_open: true
    tty: true
    volumes:
      # Keep DSpace assetstore directory between reboots
      - ./data/assetstore:/dspace/assetstore
      - ./data/dspace_logs/dspace:/dspace/log/:rw
      - ./data/dspace_logs/tomcat:/usr/local/tomcat/logs/:rw
  # DSpace PostgreSQL database container
  dspacedb:
    restart: unless-stopped
    container_name: dspacedb
    image: postgres:13
    environment:
      PGDATA: /pgdata
      POSTGRES_ADMIN_USER: postgres
      POSTGRES_ADMIN_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      dspacenet:
    ports:
    - published: 5432
      target: 5432
    stdin_open: true
    tty: true
    volumes:
      # Keep Postgres data directory between reboots
      - ./data/pgdata:/pgdata
  # DSpace Solr container
  dspacesolr:
    restart: unless-stopped
    container_name: dspacesolr
    image: "${DOCKER_OWNER:-dspace}/dspace-solr:${DSPACE_VER:-dspace-7_x}"
    build:
      context: ./dspace/src/main/docker/dspace-solr/
      # Provide path to Solr configs necessary to build Docker image
      additional_contexts:
        solrconfigs: ./dspace/solr/
      args:
        SOLR_VERSION: "${SOLR_VER:-8.11}"
    networks:
      dspacenet:
    ports:
    - published: 8983
      target: 8983
    stdin_open: true
    tty: true
    working_dir: /var/solr/data
#    volumes:
    # Keep Solr data directory between reboots
#      - ./data/solrData:/var/solr/data
    # Initialize all DSpace Solr cores then start Solr:
    # * First, run precreate-core to create the core (if it doesn't yet exist). If exists already, this is a no-op
    # * Second, copy configsets to this core:
    #   Updates to Solr configs require the container to be rebuilt/restarted: `docker compose -p d7 up -d --build dspacesolr`
    environment:
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
    entrypoint:
      - /bin/bash
      - '-c'
      - |
        init-var-solr
        precreate-core authority /opt/solr/server/solr/configsets/authority
        cp -r /opt/solr/server/solr/configsets/authority/* authority
        precreate-core oai /opt/solr/server/solr/configsets/oai
        cp -r /opt/solr/server/solr/configsets/oai/* oai
        precreate-core search /opt/solr/server/solr/configsets/search
        cp -r /opt/solr/server/solr/configsets/search/* search
        precreate-core statistics /opt/solr/server/solr/configsets/statistics
        cp -r /opt/solr/server/solr/configsets/statistics/* statistics
        precreate-core qaevent /opt/solr/server/solr/configsets/qaevent
        cp -r /opt/solr/server/solr/configsets/qaevent/* qaevent
        precreate-core suggestion /opt/solr/server/solr/configsets/suggestion
        cp -r /opt/solr/server/solr/configsets/suggestion/* suggestion
        exec solr -f
  dspacestatistics:
    restart: unless-stopped
    container_name: dspacestatistics
    image: "${DOCKER_OWNER:-dspace}/dspace-statistics:${DSPACE_VER:-dspace-7_x}"
    build:
      context: ./dspace-statistics-api-js
    networks:
      dspacenet:
    ports:
      - published: 3016
        target: 3017
    stdin_open: true
    tty: true
    working_dir: /dspace-statistics-api-js
    entrypoint:
      - /bin/bash
      - '-c'
      - |
        npm run start:dev